### ISSUE TITLE
session_start() cannot send session cache limiter - headers already sent in cron jobs

### ISSUE THREAD

**Issue by ArturMoczulski** [rollbar/rollbar-php-wordpress#86]
There seems to be a problem with the plugin when running Wordpress cron jobs. Included is a screenshot of the stack trace.
<img width="871" alt="Screen Shot 2019-09-08 at 11 08 50 PM" src="https://user-images.githubusercontent.com/2106631/64494478-b3c89700-d28d-11e9-845f-706b65bab766.png">

**Comment by squatto** [comment]
This is causing me to go over my usage limits. Definitely a problem.

**Comment by ArturMoczulski** [comment]
@squatto please contact our support @ https://docs.rollbar.com/docs (right bottom corner chat icon) to receive a usage credit

We understand that this is an inconvenience and are doing our best to resolve it asap.

**Comment by ArturMoczulski** [comment]
I believe this should be now fixed in release v2.6.1

Please, do let us know if there are further issues

**Comment by mike22** [comment]
still not fixed for me :/ And according to other similar issues here I am not the only one

**Comment by squatto** [comment]
Definitely not fixed. I upgraded my plugin and had to reapply the manual fix to prevent overloading my Rollbar account with errors again.
